export const EnvVariables = {
  NODE_MODE: "NODE_MODE",

  TG_BOT_TOKEN: "TG_BOT_TOKEN",
  TG_BOT_PORT: "TG_BOT_PORT",

  SERVER_URL: "SERVER_URL",
  DOMAIN_URL: "DOMAIN_URL",

  REDIS_PORT: "REDIS_PORT",
  REDIS_PASSWORD: "REDIS_PASSWORD",

  BOT_SERVICE_NAME: "BOT_SERVICE_NAME",
};
